# Generated by Django 4.0.2 on 2022-04-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='doctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.doctor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.patient'),
        ),
    ]
