# Generated by Django 4.0.2 on 2022-04-18 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0003_alter_address_doctorid_alter_address_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='address',
            name='patientId',
        ),
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
