# Generated by Django 4.0.2 on 2022-04-20 17:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/'), upload_to=''),
        ),
    ]
